-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) as revenue
FROM customer_shopping_behavior_cleaned
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,purchase_amount
from customer_shopping_behavior_cleaned
where discount_applied='yes' and purchase_amount >= (select AVG(purchase_amount ) from customer_shopping_behavior_cleaned);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS `average product rating`
FROM 
    customer_shopping_behavior_cleaned
GROUP BY 
    item_purchased
ORDER BY 
    AVG(review_rating) DESC
    limit 5;
    
    
    -- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS `avg_purchase_amount`
FROM customer_shopping_behavior_cleaned
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_shopping_behavior_cleaned
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;   -- order by highest revenue first


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(100.0 * SUM(CASE WHEN LOWER(discount_applied) = 'yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer_shopping_behavior_cleaned
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, Loyal (based on previous_purchases) and show counts
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping_behavior_cleaned
)
SELECT 
    customer_segment,
    COUNT(*) AS `number_of_customers`
FROM customer_type
GROUP BY customer_segment;


-- Q8. Top 3 most purchased products within each category
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_shopping_behavior_cleaned
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


-- Q9. Are repeat buyers (>5 previous purchases) likely to subscribe?
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer_shopping_behavior_cleaned
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. Revenue contribution of each age group
SELECT 
    age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_shopping_behavior_cleaned
GROUP BY age_group
ORDER BY total_revenue DESC;

